name: Test Build (No Secrets Required)

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local only)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: nself-admin:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Test image
        run: |
          docker run --rm nself-admin:test --version || true
          
      - name: Build summary
        run: |
          echo "### ✅ Build Test Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Docker image built successfully without requiring any secrets." >> $GITHUB_STEP_SUMMARY
          echo "This workflow can be used to test builds in forks and PRs." >> $GITHUB_STEP_SUMMARY